name = "cloudflare-condominium"
main = "index.js"
compatibility_date = "2025-11-30"

[[d1_databases]]
binding = "DB"  # this is how your code references the database
database_name = "cloudflare_condominium_db"
database_id = "98bbd139-7557-4cdd-a8e8-61a724be7c80"
